dcore:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST', '') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int}}"
      user: "{{ env_var('CLICKHOUSE_DBT_USERNAME', '') }}"
      password: "{{ env_var('CLICKHOUSE_DBT_PASSWORD', '') }}"
      use_lw_deletes: True
