import os
import requests.auth
from dagster import EnvVar

POSTGRES_HOST = os.getenv("POSTGRES_HOST", "")
POSTGRES_PORT = int(os.getenv("POSTGRES_PORT", 5432))

CLICKHOUSE_HOST = os.getenv("CLICKHOUSE_HOST", "")
CLICKHOUSE_PORT = int(os.getenv("CLICKHOUSE_PORT", 8123))
CLICKHOUSE_DATABASE = os.getenv("CLICKHOUSE_DATABASE", "")

CLICKHOUSE_DBT_USERNAME = EnvVar("CLICKHOUSE_DBT_USERNAME")
CLICKHOUSE_DBT_PASSWORD = EnvVar("CLICKHOUSE_DBT_PASSWORD")
