version: 2

models:
  - name: raw_tagging__tagging
    description: "This table contains raw tagging records from tagging database. Tagging table serves as a centralized system for assigning and managing tags across various entities in the system. It enables flexible querying from both perspectives—entities and tags—allowing for dynamic categorization and retrieval of information. Each record associates an entity, identified by its type and ID, with a tag, specifying the duration of its validity along with creation and update metadata."
    columns:
      - name: id
        description: "The primary key for the tagging table."
        data_type: UUID
        data_tests:
          - unique
          - not_null
      - name: entity_type
        description: "Entity to be tagged (e.g., approval request, transaction, customer etc.)"
        data_type: String
        data_tests:
          - not_null
      - name: entity_id
        description: "Unique identifier of the entity to be tagged"
        data_type: UUID
        data_tests:
          - not_null
      - name: tag
        description: "The tag assigned to an entity, such as a customer-type entity tagged as 'fraudulent'."
        data_type: String
        data_tests:
          - not_null
      - name: metadata
        description: "Includes additional metadata in a JSON-encoded string necessary for assigning or identifying the tag."
        data_type: String
      - name: create_metadata
        description: "Stores metadata related to the request session attribute's creation in a JSON-encoded string, including the creation timestamp and details of the Actor responsible for creating the request session attribute."
        data_type: String
        data_tests:
          - not_null
      - name: update_metadata
        description: "Stores metadata related to the request session attribute's updation in a JSON-encoded string, including the updation timestamp and details of the Actor responsible for updating the request session attribute."
        data_type: String
        data_tests:
          - not_null
      - name: active_from
        description: "The timestamp indicating when the entity was tagged."
        data_type: DateTime64(6, 'GMT')
        data_tests:
          - not_null
      - name: active_to
        description: "The timestamp indicating when the tag is no longer active for the entity."
        data_type: Nullable(DateTime64(6, 'GMT'))
