version: 2

models:
  - name: raw_product_definition__activations
    description: "This table contains raw activations records from Product Definition database. Each record includes a unique identifier for the activation, the activated entity (e.g., handler, component, component group), its parent entity, and creation metadata."
    columns:
      - name: id
        description: "The primary key for the activations table, uniquely identifying each activation record."
        data_type: UUID
        data_tests:
          - unique
          - not_null
      - name: activated_id
        description: "A unique identifier for the entity being activated e.g., handler, component or component group"
        data_type: UUID
        data_tests:
          - not_null
      - name: parent_id
        description: "A unique identifier representing a component, component group, or handler. If activated_id corresponds to a handler, parent_id will point to the related component."
        data_type: Nullable(UUID)
      - name: create_metadata
        description: "Stores metadata related to the activation's creation in a JSON-encoded string, including the creation timestamp and details of the Actor responsible for creating the parameter."
        data_type: String

  - name: raw_product_definition__component_groups
    description: "This table contains raw component group records from Product Definition database. Each record includes a set of components, component group name, its description, and creation and update metadata. These component groups enhance reusability by allowing a predefined set of components to be used across different product definitions."
    columns:
      - name: id
        description: "The primary key for the component_groups table, uniquely identifying each group."
        data_type: UUID
        data_tests:
          - unique
          - not_null
      - name: components
        description: "A JSONB-encoded string containing a list of all types of components associated with this component group."
        data_type: String
        data_tests:
          - not_null
      - name: create_metadata
        description: "Stores metadata related to the component group's creation in a JSON-encoded string, including the creation timestamp and details of the Actor responsible for creating the component group."
        data_type: String
      - name: update_metadata
        description: "Stores metadata related to the component group's updaion in a JSON-encoded string, including the updation timestamp and details of the Actor responsible for updating the component group."
        data_type: String
      - name: name
        description: "The name assigned to the component group for identification."
        data_type: String
        data_tests:
          - not_null
      - name: description
        description: "A textual explanation describing the component group's purpose and functionality."
        data_type: String

  - name: raw_product_definition__components
    description: "This table contains raw components records from Product Definition database. Each record contains details about the handler associated with the component, the event triggered upon executing the handler, and the component's name and description. Each component has a single attached handler."
    columns:
      - name: id
        description: "The primary key for the components table, uniquely identifying each component."
        data_type: UUID
        data_tests:
          - unique
          - not_null
      - name: event
        description: "The event triggered by the component."
        data_type: String
        data_tests:
          - not_null
      - name: handler_id
        description: "A unique identifier referencing the handler attached to this component."
        data_type: UUID
        data_tests:
          - not_null
      - name: create_metadata
        description: "Stores metadata related to the component group's creation in a JSON-encoded string, including the creation timestamp and details of the Actor responsible for creating the component group."
        data_type: String
      - name: update_metadata
        description: "Stores metadata related to the component group's updation in a JSON-encoded string, including the updation timestamp and details of the Actor responsible for updating the component group."
        data_type: String
          - not_null
      - name: name
        description: "The name assigned to the component for identification."
        data_type: String
        data_tests:
          - not_null
      - name: description
        description: "A textual explanation describing the component's purpose and functionality."
        data_type: String

  - name: raw_product_definition__handlers
    description: "This table contains raw handlers records from Product Definition database. Each record contains various details about a handler, including its type, code, programming language, name, description, required inputs, and creation and update metadata. This table is useful for defining the execution logic behind actions such as transactions, account creation, and more."
    columns:
      - name: id
        description: "The primary key for the handlers table, uniquely identifying each handler."
        data_type: UUID
        data_tests:
          - unique
          - not_null
      - name: type
        description: "Indicates the event or action the handler is designed for, such as Account, Transaction, or Scheduled (for scheduled events)."
        data_type: String
        data_tests:
          - not_null
      - name: lang
        description: "Indicates the programming language in which the handler's code is written."
        data_type: String
        data_tests:
          - not_null
      - name: handler
        description: "Stores the script for processing various event types in the specified programming language."
        data_type: String
        data_tests:
          - not_null
      - name: create_metadata
        description: "Stores metadata related to the handler's creation in a JSON-encoded string, including the creation timestamp and details of the Actor responsible for creating the handler."
        data_type: String
      - name: update_metadata
        description: "Stores metadata related to the handler's updaion in a JSON-encoded string, including the updation timestamp and details of the Actor responsible for updating the handler."
        data_type: String
          - not_null
      - name: name
        description: "The name assigned to the handler for identification."
        data_type: String
        data_tests:
          - not_null
      - name: description
        description: "A textual explanation describing the handler's purpose and functionality."
        data_type: String
      - name: is_static
        description: "Indicates whether the handler can be executed without an account or transaction request."
        data_type: Bool
        data_tests:
          - not_null
      - name: inputs
        description: "A JSONB-encoded string which consists of inputs required (if any) to execute the script."
        data_type: String
      - name: request_metadata
        description: "A JSON-encoded string which consists of additional metadata related to the handler's execution or request context."
        data_type: String

  - name: raw_product_definition__product_definitions
    description: "This table contains raw product definitions records from Product Definition database. Each record contains a list of components required for a product's execution, any necessary fields for product setup, the product's name, description, and associated account type. It also includes creation and update metadata, along with a family ID that groups different revisions of the product."
    columns:
      - name: id
        description: "The primary key for the product_definitions table, uniquely identifying each product."
        data_type: UUID
        data_tests:
          - unique
          - not_null
      - name: scheduled_events
        description: "A JSONB-encoded string that schedules the execution of handler if needed, specifying the timing or frequency using cron expressions."
        data_type: String
        data_tests:
          - not_null
      - name: components
        description: "A JSONB-encoded string field containing a list of components, including inline components, components, and component groups associated with this product."
        data_type: String
        data_tests:
          - not_null
      - name: requirements
        description: "A JSONB field capturing product-specific requirements, such as allowed transactions or owner types for the product."
        data_type: String
        data_tests:
          - not_null
      - name: create_metadata
        description: "Stores metadata related to the product definition's creation in a JSON-encoded string, including the creation timestamp and details of the Actor responsible for creating the product definition."
        data_type: String
      - name: update_metadata
        description: "Stores metadata related to the product definition's updation in a JSON-encoded string, including the updation timestamp and details of the Actor responsible for updating the product definition."
        data_type: String
          - not_null
      - name: name
        description: "The name assigned to the product definition for identification."
        data_type: String
        data_tests:
          - not_null
      - name: description
        description: "A textual explanation providing details about the product definition."
        data_type: String
      - name: type
        description: "Indicates the type of account linked to the product definition, such as SYSTEM or CUSTOMER."
        data_type: String
        data_tests:
          - not_null
          - accepted_values:
              values: "{{ var('product_def_types') }}"
      - name: metadata
        description: "A JSON-encoded string holding additional metadata related to the product."
        data_type: String
        data_tests:
          - not_null
      - name: family_id
        description: A unique identifier that associates a product with its family or group. When a product is migrated to a new version, its product definition ID changes. This ID ensures the product can be uniquely identified across different versions."
        data_type: UUID
        data_tests:
          - not_null

  - name: raw_product_definition__system_settings
    data_tests:
      - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - type
                - value
    description: "This table contains raw system settings records from Product Definition database. Each record contains system settings for product definitions, including the handler's programming language, type, active status, and creation and update metadata."
    columns:
      - name: id
        description: "The primary key for the system_settings table, uniquely identifying each system setting."
        data_type: UUID
        data_tests:
          - unique
          - not_null
      - name: type
        description: "The type of system setting specified, e.g Handler language or Handler type."
        data_type: String
        data_tests:
          - not_null
          - accepted_values:
              values: "{{ var('system_settings_types') }}"
      - name: value
        description: "The value corresponding to the system setting type, such as a language name (e.g., KOTLIN) or a handler type (e.g., TXN)."
        data_type: String
        data_tests:
          - not_null
      - name: active
        description: "A boolean flag specifying whether or not a specific system setting is active"
        data_type: Bool
        data_tests:
          - not_null
      - name: create_metadata
        description: "Stores metadata related to the system setting's creation in a JSON-encoded string, including the creation timestamp and details of the Actor responsible for creating the system setting."
        data_type: String
      - name: update_metadata
        description: "Stores metadata related to the system setting's updation in a JSON-encoded string, including the updation timestamp and details of the Actor responsible for updating the system setting."
        data_type: String
          - not_null
